---
title: "Grant & Longstreet"
subtitle: "An\nOpposing\nFriendship"
authors: "Randy Green | Daniel Hadidon | Geoffrey Reed"
output:
    powerpoint_presentation:
        slide_level: 2
        reference_doc: "learning_team_presentation_style_reference.pptx"
---


```{r setup, echo = FALSE, cache = FALSE}
knitr::opts_knit$set(eval.after = 'fig.cap')
knitr::opts_chunk$set(echo = FALSE)
knitr::read_chunk('learning_team_presentation_analysis.R')
```

## Texts

###### *Personal Memoirs of U. S. Grant*

- Ulysses S. Grant

###### *From Manassas to Appomattox: Memoirs of the Civil War in America*

- by James Longstreet


## Introductions

- Who were these guys? (30-second version)
- Who are we? (10-second version)


## Topics

- Orientations
- Summary Statistics
- Frequency Analysis
- Token Distribution Analysis
- Correlation Analysis
- Type-Token Ratio
- Hapax Richness
- KWIC
- Sentiment Analysis
- Conclusions


# Orientations


---
- (Can be several slides)
- Who were these men? (Longer version!)
- Why were they important?
- When did they meet?
- What time period do their writings cover?
- What *chapters* most concern their interactions?
- Which *chapters* cover the same subject matter? (Graphic?)


# Summary Statistics


---

- Number of chapters, paragraphs, sentences, and words?
- Words per sentence, paragraph, and chapter? (Min, max, mean, etc.)
- How about *by* chapter, *per* something else? (Trends?!)
- Sentences per paragraph and chapter? (Min, max, mean, etc.)
- Paragraphs per chapter? (Min, max, mean, etc.)
- Word length? By chapter?
- How about punctuation?
  - Total punctiation?
  - Relative use of punctuation?
  - Punctuation per sentence, paragraph, chapter?
  - GRAPHIC (strip out all but punctuation!, show differences!)
- This is *a lot*---wrap up in a couple of graphics?


# Frequency Analysis


---

- Introduce stopword list
- Most frequent words, bigrams, trigrams (Cleveland dot)
- Most frequent words, bigrams, trigrams *by chapter* (Cleveland dod)
- **No wordcloud** because hackneyed
- Inverse document frequency? TF-IDF?
- TF-IDF between texts? (word, bigram, trigram + graphic)
- TF-IDF between chapters of a single texts? (word, bigram, trigram + graphic)


# Token Distribution Analysis


---

- Pick some words! (Arbitrary! Cherry picking!)
- How about highlights off frequency and TF-IDF?
- GRAPHIC dual distro plot with chapter, paragraph, and sentence backgrounds
  - Maybe highlight events from orientation?
  - Maybe highlight events in the war?


# Correlation Analysis


---

- Pick some words! (Arbitrary! Cherry picking!)
- How about highlights off frequency and TF-IDF?
- GRAPHIC for each set of interesting words?


# Type-Token Ratio


---

- TTR by chapter graphic?


# Hapax Richness


---

- Not just hapax, also dis, tris, tetrakis
- How about bigrams? Trigrams?
- Shared hapax...
- Maybe Venn diagram graphic?
- Zipf's Law GRAPHIC

# KWIC


---

- How much context?
- Which words? How about *shared* hapax, dis tris, tetrakis?
- How about TF-IDF words?
- Does context help or just reinforce beliefs?


# Sentiment Analysis


---

- Which sentiment dictionary?
- How to handle negatives?
- Show how many words missing from sentiment dictionary?
- Stemming? (Is it available?)
- Compare/contrast results and output?
- Sentiments over time? GRAPHIC..
  - How does the sentiment compare to their fortunes?
  - How does the sentiment compare with the progress of the war?


# Conclusions


---

- TBD---do analysis first!


# Questions
